### ISSUE TITLE
little error

### ISSUE THREAD

**Issue by numerized** [clubinvest/binance-min-amount#1]
you've got a typo:
```
module.exports.getMinAmout = getMinAmout;
```

**Comment by numerized** [comment]
getMinAmout is badly written all over :)

**Comment by rodrigooler** [comment]
Sorry for the delay, things were raced here. I just uploaded version 0.0.10 which is fixed and added new tests to get the minQty of the pairs you want existing in binance.

If there is an error or a new suggestion, just open the call! Thank you for your contribution!

https://github.com/clubinvest/binance-min-amount/blob/master/src/index.js#L71

**Comment by numerized** [comment]
Thanks a lot.

**Comment by numerized** [comment]
Have you updated npm though ?? I get version 0.0.8 from there.
